name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        model: [ "G973F" ]

    steps:
    - uses: actions/checkout@v1
    - name: Install mkbootimg
      run: |
        wget -q https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/refs/heads/master.tar.gz -O - | tar xzf - mkbootimg.py
        chmod +x mkbootimg.py
        sudo mv mkbootimg.py /usr/local/bin/mkbootimg
    - name: Install avbtool
      run: |
        wget -q https://android.googlesource.com/platform/external/avb/+archive/refs/heads/android10-dev.tar.gz -O - | tar xzf - avbtool
        chmod +x avbtool
        sudo mv avbtool /usr/local/bin/avbtool
    - name: Clone Submodules
      run: git submodule update --init --recursive
    - name: Enable KVM
      run: |
          for file in $(find -name 'exynos9820*_defconfig'); do
            echo "Modifying $file ..."
            echo >> "$file"
            echo 'CONFIG_VIRTUALIZATION=y' >> "$file"
            echo 'CONFIG_KVM=y' >> "$file"
            echo 'CONFIG_KVM_MMIO=y' >> "$file"
            echo 'CONFIG_KVM_ARM_HOST=y' >> "$file"
          done
    - name: Kernel Configure
      run: |
        ./build config                   \
                model=${{ matrix.model}} \
                name="ThunderStormsKernel"        \
                +magisk                  \
                +ttl                     \
                +wireguard               \
                +cifs                    \
                +sdfat                   \
                +ntfs                    \
                +morosound               \
                +boeffla_wl_blocker      \
                +ts_config               \
        2>&1 | tee config.info
    - name: Kernel Build
      run: ./build :build
    - name: Create boot.img
      run: ./build :mkimg
    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: ThunderStormsKernel-${{ matrix.model }}
        path: boot.img
    - name: Upload Kernel Info
      uses: actions/upload-artifact@v2
      with:
        name: ConfigurationInfo-${{ matrix.model }}
        path: config.*
