name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install mkbootimg
      run: |
        wget -q https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/refs/heads/master.tar.gz -O - | tar xzf - mkbootimg.py
        chmod +x mkbootimg.py
        sudo mv mkbootimg.py /usr/local/bin/mkbootimg
    - name: Install avbtool
      run: |
        wget -q https://android.googlesource.com/platform/external/avb/+archive/refs/heads/android10-dev.tar.gz -O - | tar xzf - avbtool
        chmod +x avbtool
        sudo mv avbtool /usr/local/bin/avbtool
    - name: Install toolchain
      run: |
        git submodule deinit --force --all
        rm -fr toolchain
        git add .
        mkdir toolchain
        git submodule add --branch proton --depth 1 https://github.com/CruelKernel/samsung-exynos9820-toolchain toolchain/proton
        sudo mkdir -p /home/nalas/kernel/AiO-S10-TS
        sudo git clone --depth 1 -j $(nproc) --branch default --single-branch https://github.com/CruelKernel/samsung-exynos9820-toolchain /home/nalas/kernel/AiO-S10-TS/toolchain
    - name: Enable KVM
      run: |
          for file in $(find -name 'exynos9820*_defconfig'); do
            echo "Modifying $file ..."
            echo >> "$file"
            echo 'CONFIG_VIRTUALIZATION=y' >> "$file"
            echo 'CONFIG_KVM=y' >> "$file"
            echo 'CONFIG_KVM_MMIO=y' >> "$file"
            echo 'CONFIG_KVM_ARM_HOST=y' >> "$file"
          done
    - name: Kernel Build
      run: echo 7 | ./ts-build-proton.sh
    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: ThunderStormsKernel
        path: ./*.zip
